kind: Service
apiVersion: v1
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  loadBalancerIP: 192.168.99.201
  ports:
    - name: ftp-transfer-active
      protocol: TCP
      port: 20
      targetPort: 20
    - name: ftp-connection
      protocol: TCP
      port: 21
      targetPort: 21
    - name: ftp-passive-21000
      protocol: TCP
      port: 30020
      targetPort: 30020
    - name: ftp-passive-21001
      protocol: TCP
      port: 30021
      targetPort: 30021
    - name: ftp-passive-21002
      protocol: TCP
      port: 30022
      targetPort: 30022
    - name: ftp-passive-21003
      protocol: TCP
      port: 30023
      targetPort: 30023
    - name: ftp-passive-21004
      protocol: TCP
      port: 30024
      targetPort: 30024
    - name: ftp-passive-21005
      protocol: TCP
      port: 30025
      targetPort: 30025
    - name: ftp-passive-21006
      protocol: TCP
      port: 30026
      targetPort: 30026
    - name: ftp-passive-21007
      protocol: TCP
      port: 30027
      targetPort: 30027
    - name: ftp-passive-21008
      protocol: TCP
      port: 30028
      targetPort: 30028
    - name: ftp-passive-21009
      protocol: TCP
      port: 30029
      targetPort: 30029
    - name: ftp-passive-21010
      protocol: TCP
      port: 30030
      targetPort: 30030
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      restartPolicy: Always
      containers:
      - name: ftps
        image: ftps:latest
        imagePullPolicy: Never
        securityContext: #Mejor solo a su volumen??? Hmmm.... :?
          privileged: true
        env:
          - name: FTPS_USER
            valueFrom:
              secretKeyRef:
                name: ftps-auth
                key: username
          - name: FTPS_PASS
            valueFrom:
              secretKeyRef:
                name: ftps-auth
                key: password
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 30020
        - containerPort: 30021
        - containerPort: 30022
        - containerPort: 30023
        - containerPort: 30024
        - containerPort: 30025
        - containerPort: 30026
        - containerPort: 30027
        - containerPort: 30028
        - containerPort: 30029
        - containerPort: 30030
        volumeMounts:
          - name: ftps-chroot
            mountPath: "/ftps_chroot"
            readOnly: false
      volumes:
        - name: ftps-chroot
          hostPath:
            path: /Users/mrosario/ft_services/srcs/ftps/ftps_chroot #don't know how to do $USER or (whoami) here. Hmm....