kind: Service
apiVersion: v1
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
    - name: influxdb
      protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      restartPolicy: Always
      containers:
      - name: influxdb
        image: influxdb:latest
        imagePullPolicy: Never
        securityContext: #Mejor solo a su volumen??? Hmmm.... :?
          privileged: true
        #env:
        #  - name: MYSQL_USER
        #    valueFrom:
        #      secretKeyRef:
        #        name: mysql-auth
        #        key: username
        #  - name: MYSQL_PASS
        #    valueFrom:
        #      secretKeyRef:
        #        name: mysql-auth
        #        key: password
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: "root/.influxdb/"
          readOnly: false
      volumes:
        - name: influxdb-persistent-storage
          persistentVolumeClaim:
            claimName: influxdb-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 24Mi