kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.200
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: ssh
      port: 22
      targetPort: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Never
        securityContext: #This pod really needs privileged access to host? :? Hmmmm
          privileged: true
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
        env:
          - name: SSL_USER
            valueFrom:
              secretKeyRef:
                name: nginx-ssh
                key: username
          - name: SSL_PASS
            valueFrom:
              secretKeyRef:
                name: nginx-ssh
                key: password
        volumeMounts:
          - mountPath: "/etc/nginx/ssl/"
            name: nginx-ssl
            readOnly: true
      volumes:
        - name: nginx-ssl
          secret:
            secretName: nginx-ssl